spring:
  thymeleaf:
    cache: false
    mode: HTML5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: tkGoods
    #username: taoke
    password: tkGoods
    #password: taoke
    url: jdbc:mysql://101.132.102.102/tkGoods?characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://139.224.119.167/taoke?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    generate-ddl: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
    static-locations:
            classpath:/static/css/,classpath:/static/css/bootstrap/,classpath:/static/images/,classpath:/static/js/,classpath:/static/js/bootstrap/,
            classpath:/static/ueditor/
server:
  context-path: /tkGoods

#图片根路径
uploadImage:
  #root: F:/
  root: /project/
  path: images/
  #uriRoot: http://localhost:8080/tkGoods/images/
  uriRoot: http://101.132.102.102:8080/tkGoods/images/


