spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name:com.mysql.jdbc.Driver
    username: taoke
    password: taoke
    url: jdbc:mysql://139.224.119.167/taoke?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /tkGoods